name: Slack
#uses: 8398a7/action-slack@v3.8.0

on: 
  push:
    branches: 
      - develop
    paths:
      - "index.html"

jobs:
  slack:
    # Ubuntu
    runs-on: ubuntu-latest
    steps:
      # Slack
      - name: Slack Notification
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: "<@ebata_ryou> :warning:composer.jsonが更新されました！:warning:"
