name: Slack
#uses: 8398a7/action-slack@v3.8.0

on: 
  push:
    paths:
      - "index.html"

jobs:
  slack:
    # Ubuntu
    runs-on: ubuntu-latest
    steps:
      # Slack
      - name: Slack Notification
        uses: 
          - tokorom/action-slack-incoming-webhook@main
          - 8398a7/action-slack@v3.8.0
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          mention: '@ebata_ryou'
          text: ":warning:composer.jsonが更新されました！:warning:"
