name: Slack

on: 
  push:
    paths:
      - "index.html"

env:
  SLACK_USERNAME: Composer-Install
  SLACK_ICON: https://example.com/image/icon_bot.png

jobs:
  slack:
    # Ubuntu
    runs-on: ubuntu-latest
    steps:
      # Slack
      - name: Slack Notification
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: "⚠️composer.jsonが更新されました！⚠️"
